"""remove hello

Revision ID: 1354233cdf98
Revises: f6e8dbd1c551
Create Date: 2022-02-15 17:06:26.552964

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1354233cdf98'
down_revision = 'f6e8dbd1c551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('variable_overhead', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('country', 'commodity')
    )
    op.drop_index('ix_hello_id', table_name='hello')
    op.drop_index('ix_hello_message', table_name='hello')
    op.drop_table('hello')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hello_message', 'hello', ['message'], unique=False)
    op.create_index('ix_hello_id', 'hello', ['id'], unique=False)
    op.drop_table('vendors')
    # ### end Alembic commands ###
