"""first migration

Revision ID: aff96c9b9167
Revises: 
Create Date: 2022-02-15 19:03:06.517842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aff96c9b9167'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('variable_overhead', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('country', 'commodity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    # ### end Alembic commands ###
