"""first migration

Revision ID: f6e8dbd1c551
Revises: 
Create Date: 2022-02-15 12:12:16.466818

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f6e8dbd1c551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hello_id'), 'hello', ['id'], unique=False)
    op.create_index(op.f('ix_hello_message'), 'hello', ['message'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hello_message'), table_name='hello')
    op.drop_index(op.f('ix_hello_id'), table_name='hello')
    op.drop_table('hello')
    # ### end Alembic commands ###
